"""Pydantic data models for the opencode REST API (wire-format aware).

All models inherit :class:`OpencodeModel`, which maps snake_case Python
fields to the server's camelCase wire format (with uppercase ``ID``
suffixes, e.g. ``session_id`` -> ``sessionID``). Import models from the
package root or from this submodule; deep submodule paths
(``models.part`` etc.) are implementation details.
"""

from __future__ import annotations

from .base import OpencodeModel
from .discover import Agent, Command, Health, Model, Provider, ProviderList, ServerConfig, Skill
from .event import (
    EVENT_CATALOG,
    Event,
    EventType,
    MessagePartDeltaEvent,
    MessagePartDeltaPayload,
    MessagePartUpdatedEvent,
    MessageUpdatedEvent,
    PermissionAskedEvent,
    QuestionAskedEvent,
    SessionIdleEvent,
    typed_event,
)
from .interaction import (
    PermissionRequest,
    PermissionTool,
    QuestionAnswer,
    QuestionInfo,
    QuestionOption,
    QuestionRequest,
    QuestionTool,
)
from .mcp import (
    McpConfig,
    McpLocalConfig,
    McpOAuthConfig,
    McpRemoteConfig,
    MCPStatus,
    MCPStatusConnected,
    MCPStatusDisabled,
    MCPStatusFailed,
    MCPStatusNeedsAuth,
    MCPStatusNeedsClientRegistration,
)
from .message import (
    AssistantMessage,
    AssistantMessagePath,
    Message,
    MessageTime,
    MessageWithParts,
    UserMessage,
    UserMessageModel,
    UserMessageSummary,
)
from .part import (
    AgentPart,
    AgentPartInput,
    AssistantMessageTokens,
    CompactionPart,
    FilePart,
    FilePartInput,
    FilePartRange,
    FilePartSource,
    FilePartSourceFile,
    FilePartSourceResource,
    FilePartSourceSymbol,
    FilePartText,
    Part,
    PartBase,
    PartTime,
    PatchPart,
    PromptModel,
    PromptPart,
    PromptRequest,
    ReasoningPart,
    RetryPart,
    SnapshotPart,
    StepFinishPart,
    StepStartPart,
    SubtaskModel,
    SubtaskPartInput,
    TextPart,
    TextPartInput,
    ToolPart,
    ToolState,
    ToolStateCompleted,
    ToolStateError,
    ToolStatePending,
    ToolStateRunning,
)
from .session import (
    CreateSessionRequest,
    ModelID,
    PermissionRule,
    PermissionRuleset,
    Session,
    SessionFileDiff,
    SessionShare,
    SessionSnapshot,
    SessionStatus,
    SessionStatusBusy,
    SessionStatusIdle,
    SessionStatusRetry,
    SessionStatusRetryAction,
    SessionTime,
    SessionTokenCache,
    SessionTokens,
    Todo,
    UpdateSessionRequest,
)
from .vcs import VcsFileDiff, VcsFileStatus, VcsInfo

__all__ = [
    "Agent",
    "AgentPart",
    "AgentPartInput",
    "AssistantMessage",
    "AssistantMessagePath",
    "AssistantMessageTokens",
    "Command",
    "CompactionPart",
    "CreateSessionRequest",
    "EVENT_CATALOG",
    "Event",
    "EventType",
    "FilePart",
    "FilePartInput",
    "FilePartRange",
    "FilePartSource",
    "FilePartSourceFile",
    "FilePartSourceResource",
    "FilePartSourceSymbol",
    "FilePartText",
    "Health",
    "Message",
    "MessagePartDeltaEvent",
    "MessagePartDeltaPayload",
    "MessagePartUpdatedEvent",
    "MessageTime",
    "MessageUpdatedEvent",
    "MessageWithParts",
    "MCPStatus",
    "MCPStatusConnected",
    "MCPStatusDisabled",
    "MCPStatusFailed",
    "MCPStatusNeedsAuth",
    "MCPStatusNeedsClientRegistration",
    "McpConfig",
    "McpLocalConfig",
    "McpOAuthConfig",
    "McpRemoteConfig",
    "Model",
    "ModelID",
    "OpencodeModel",
    "Part",
    "PartBase",
    "PartTime",
    "PatchPart",
    "PermissionAskedEvent",
    "PermissionRequest",
    "PermissionRule",
    "PermissionRuleset",
    "PermissionTool",
    "PromptModel",
    "PromptPart",
    "PromptRequest",
    "Provider",
    "ProviderList",
    "QuestionAnswer",
    "QuestionAskedEvent",
    "QuestionInfo",
    "QuestionOption",
    "QuestionRequest",
    "QuestionTool",
    "ReasoningPart",
    "RetryPart",
    "ServerConfig",
    "Session",
    "SessionFileDiff",
    "SessionIdleEvent",
    "SessionShare",
    "SessionSnapshot",
    "SessionStatus",
    "SessionStatusBusy",
    "SessionStatusIdle",
    "SessionStatusRetry",
    "SessionStatusRetryAction",
    "SessionTime",
    "SessionTokenCache",
    "SessionTokens",
    "Skill",
    "SnapshotPart",
    "StepFinishPart",
    "StepStartPart",
    "SubtaskModel",
    "SubtaskPartInput",
    "TextPart",
    "TextPartInput",
    "Todo",
    "ToolPart",
    "ToolState",
    "ToolStateCompleted",
    "ToolStateError",
    "ToolStatePending",
    "ToolStateRunning",
    "UpdateSessionRequest",
    "UserMessage",
    "UserMessageModel",
    "UserMessageSummary",
    "VcsFileDiff",
    "VcsFileStatus",
    "VcsInfo",
    "typed_event",
]
