"""Pydantic data models for the opencode REST API (wire-format aware).

All models inherit :class:`OpencodeModel`, which maps snake_case Python
fields to the server's camelCase wire format (with uppercase ``ID``
suffixes, e.g. ``session_id`` -> ``sessionID``). Import models from the
package root or from this submodule; deep submodule paths
(``models.part`` etc.) are implementation details.
"""

from __future__ import annotations

from .base import OpencodeModel
from .discover import Agent, Command, Health, Model, Provider, ProviderList, ServerConfig
from .event import Event
from .interaction import (
    PermissionRequest,
    PermissionTool,
    QuestionAnswer,
    QuestionInfo,
    QuestionOption,
    QuestionRequest,
    QuestionTool,
)
from .message import (
    AssistantMessage,
    AssistantMessagePath,
    Message,
    MessageTime,
    MessageWithParts,
    UserMessage,
    UserMessageModel,
    UserMessageSummary,
)
from .part import (
    AgentPart,
    AgentPartInput,
    AssistantMessageTokens,
    CompactionPart,
    FilePart,
    FilePartInput,
    FilePartRange,
    FilePartSource,
    FilePartSourceFile,
    FilePartSourceResource,
    FilePartSourceSymbol,
    FilePartText,
    Part,
    PartBase,
    PartTime,
    PatchPart,
    PromptModel,
    PromptPart,
    PromptRequest,
    ReasoningPart,
    RetryPart,
    SnapshotPart,
    StepFinishPart,
    StepStartPart,
    SubtaskModel,
    SubtaskPartInput,
    TextPart,
    TextPartInput,
    ToolPart,
    ToolState,
    ToolStateCompleted,
    ToolStateError,
    ToolStatePending,
    ToolStateRunning,
)
from .session import (
    CreateSessionRequest,
    ModelID,
    PermissionRule,
    PermissionRuleset,
    Session,
    SessionShare,
    SessionSnapshot,
    SessionTime,
    SessionTokenCache,
    SessionTokens,
    UpdateSessionRequest,
)

__all__ = [
    "Agent",
    "AgentPart",
    "AgentPartInput",
    "AssistantMessage",
    "AssistantMessagePath",
    "AssistantMessageTokens",
    "Command",
    "CompactionPart",
    "CreateSessionRequest",
    "Event",
    "FilePart",
    "FilePartInput",
    "FilePartRange",
    "FilePartSource",
    "FilePartSourceFile",
    "FilePartSourceResource",
    "FilePartSourceSymbol",
    "FilePartText",
    "Health",
    "Message",
    "MessageTime",
    "MessageWithParts",
    "Model",
    "ModelID",
    "OpencodeModel",
    "Part",
    "PartBase",
    "PartTime",
    "PatchPart",
    "PermissionRequest",
    "PermissionRule",
    "PermissionRuleset",
    "PermissionTool",
    "PromptModel",
    "PromptPart",
    "PromptRequest",
    "Provider",
    "ProviderList",
    "QuestionAnswer",
    "QuestionInfo",
    "QuestionOption",
    "QuestionRequest",
    "QuestionTool",
    "ReasoningPart",
    "RetryPart",
    "ServerConfig",
    "Session",
    "SessionShare",
    "SessionSnapshot",
    "SessionTime",
    "SessionTokenCache",
    "SessionTokens",
    "SnapshotPart",
    "StepFinishPart",
    "StepStartPart",
    "SubtaskModel",
    "SubtaskPartInput",
    "TextPart",
    "TextPartInput",
    "ToolPart",
    "ToolState",
    "ToolStateCompleted",
    "ToolStateError",
    "ToolStatePending",
    "ToolStateRunning",
    "UpdateSessionRequest",
    "UserMessage",
    "UserMessageModel",
    "UserMessageSummary",
]
